// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/solutions": {
    params: {};
  };
  "/solutions/:slug": {
    params: {
      "slug": string;
    };
  };
  "/portfolio": {
    params: {};
  };
  "/portfolio/:slug": {
    params: {
      "slug": string;
    };
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/solutions" | "/solutions/:slug" | "/portfolio" | "/portfolio/:slug" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/solutions/index.tsx": {
    id: "routes/solutions/index";
    page: "/solutions";
  };
  "routes/solutions/detail.tsx": {
    id: "routes/solutions/detail";
    page: "/solutions/:slug";
  };
  "routes/portfolio/index.tsx": {
    id: "routes/portfolio/index";
    page: "/portfolio";
  };
  "routes/portfolio/detail.tsx": {
    id: "routes/portfolio/detail";
    page: "/portfolio/:slug";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/solutions/index": typeof import("./app/routes/solutions/index.tsx");
  "routes/solutions/detail": typeof import("./app/routes/solutions/detail.tsx");
  "routes/portfolio/index": typeof import("./app/routes/portfolio/index.tsx");
  "routes/portfolio/detail": typeof import("./app/routes/portfolio/detail.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};